version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt   #Install any dependencies (optional)
  build:
    commands:
      - echo "Building the application"
      - python app.py  # Run the application

artifacts:
  files:
    - '**/*'  # Adjust as necessary to include all relevant files
  discard-paths: no  # Preserves the folder structure
