version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt   #Install any dependencies (optional)
  build:
    commands:
      - echo "Building the application"
      - python app.py  # Run the application
